name: "[CI] Continuous Integration"

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            # Commom CI Steps
            - uses: actions/checkout@v3
            # ------------------------------------------
            - name: "Install Dependencies"
              run: "npm ci"
            - name: "Lint"
              run: "npm run lint"
